# Generated by Django 3.2.8 on 2021-11-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='products_categories',
        ),
        migrations.AlterModelTable(
            name='option',
            table='products_options',
        ),
        migrations.AlterModelTable(
            name='optiongroup',
            table='products_option_group',
        ),
        migrations.AlterModelTable(
            name='optionitem',
            table='products_option_items',
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='products_product_variants',
        ),
        migrations.AlterModelTable(
            name='productvariantvalues',
            table='products_product_variant_values',
        ),
    ]
